I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 196, in script
    al "Empezaremos por la biblioteca y los pasillos, ¿alguien me quiere acompañar a la biblioteca?"
Exception: Sayer 'al' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 196, in script
    al "Empezaremos por la biblioteca y los pasillos, ¿alguien me quiere acompañar a la biblioteca?"
  File "C:\Program Files\Ren'Py\renpy-8.0.2-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files\Ren'Py\renpy-8.0.2-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'al' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Lexium 0.2
Wed Sep 28 18:10:16 2022
